/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package avro;
@org.apache.avro.specific.AvroGenerated
public enum CodigoBancoEnum implements org.apache.avro.generic.GenericEnumSymbol<CodigoBancoEnum> {
  _1001, _1002, _1006, _1007, _1009, _1012, _1013, _1014, _1019, _1023, _1031, _1032, _1040, _1047, _1051, _1052, _1053, _1059, _1060, _1061, _1062, _1063, _1065, _1066, _1067, _1069, _1071, _1086, _1121, _1151, _1283, _1289, _1291, _1292, _1303, _1370, _1507, _1551, _1558, _1637  ;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"enum\",\"name\":\"CodigoBancoEnum\",\"namespace\":\"avro\",\"symbols\":[\"_1001\",\"_1002\",\"_1006\",\"_1007\",\"_1009\",\"_1012\",\"_1013\",\"_1014\",\"_1019\",\"_1023\",\"_1031\",\"_1032\",\"_1040\",\"_1047\",\"_1051\",\"_1052\",\"_1053\",\"_1059\",\"_1060\",\"_1061\",\"_1062\",\"_1063\",\"_1065\",\"_1066\",\"_1067\",\"_1069\",\"_1071\",\"_1086\",\"_1121\",\"_1151\",\"_1283\",\"_1289\",\"_1291\",\"_1292\",\"_1303\",\"_1370\",\"_1507\",\"_1551\",\"_1558\",\"_1637\"]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
}
