/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package avro;
@org.apache.avro.specific.AvroGenerated
public enum EstadoRenovacionEnum implements org.apache.avro.generic.GenericEnumSymbol<EstadoRenovacionEnum> {
  POR_PROCESAR, ERROR_DATOS, EXITOSO, NO_EXITOSO  ;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"enum\",\"name\":\"EstadoRenovacionEnum\",\"namespace\":\"avro\",\"symbols\":[\"POR_PROCESAR\",\"ERROR_DATOS\",\"EXITOSO\",\"NO_EXITOSO\"]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
}
