/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package avro;
@org.apache.avro.specific.AvroGenerated
public enum NumeroProductoCDTEnum implements org.apache.avro.generic.GenericEnumSymbol<NumeroProductoCDTEnum> {
  D180, D360, D540, D541  ;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"enum\",\"name\":\"NumeroProductoCDTEnum\",\"namespace\":\"avro\",\"symbols\":[\"D180\",\"D360\",\"D540\",\"D541\"]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
}
