/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package avro;
@org.apache.avro.specific.AvroGenerated
public enum TipoRenovacionEnum implements org.apache.avro.generic.GenericEnumSymbol<TipoRenovacionEnum> {
  _1, _2, _4  ;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"enum\",\"name\":\"TipoRenovacionEnum\",\"namespace\":\"avro\",\"symbols\":[\"_1\",\"_2\",\"_4\"]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
}
