/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package avro;
@org.apache.avro.specific.AvroGenerated
public enum TipoProcesoEnum implements org.apache.avro.generic.GenericEnumSymbol<TipoProcesoEnum> {
  CANCELACION, RENOVACION  ;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"enum\",\"name\":\"TipoProcesoEnum\",\"namespace\":\"avro\",\"symbols\":[\"CANCELACION\",\"RENOVACION\"]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
}
