/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package avro;
@org.apache.avro.specific.AvroGenerated
public enum TipoTransaccionEnum implements org.apache.avro.generic.GenericEnumSymbol<TipoTransaccionEnum> {
  _37, _27  ;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"enum\",\"name\":\"TipoTransaccionEnum\",\"namespace\":\"avro\",\"symbols\":[\"_37\",\"_27\"]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
}
